sudo: required
language: minimal

env:
  global:
    - DOCKER_IMAGE=alectolytic/rpmbuilder
    - COPR_REPOSITORY=repository
    - OS_ARCH=x86_64
  matrix:
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=33 PACKAGE=helm
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=33 PACKAGE=kfctl
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=33 PACKAGE=k9s
    - OS_TYPE=fedora OS_DIST=fedora OS_VERSION=33 PACKAGE=kind

services:
  - docker

install: true

script:
  - docker run -e RPM_LINT=true -v $(pwd)/${PACKAGE}:/sources -v $(pwd):/output:Z -e "SRPM_ONLY=1" ${DOCKER_IMAGE}:${OS_TYPE}-${OS_VERSION}
